FROM node:20.11

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3000

ENTRYPOINT ["npm", "run", "start:dev"]
